### ISSUE TITLE
Testes Manuais - Bugs

### ISSUE THREAD

**Issue by paulasbia** [taiscremaschi/42_Irc#32]
##  Context
On HexChat, we can not start more than one Client with the same name, but if you try do this and changes the user after, we are not able to see the groups correctly. Also, the name continues with the first nick attempt on top of the HexChat window.

## How to reproduce

1. Start a client with nick: A, second: B, third: C and name A,
2.  Do /JOIN #group2.
3. Start a new client exactly the first, nick: A, second: B, third: C and name A,
4.  You will receive a msg: username already is use. 
5. Change USER to test and to connect. 
6. On client test, /JOIN #group2, 
7. Observe: client A will see a new client in the group, but client test can not see this channel.  

![image](https://github.com/user-attachments/assets/eedff411-91dc-4ab5-b0d7-3f1238dc5fba)

8. With client test,  /JOIN #group
9.  With client A, /JOIN #group 
10. Observe: Client A can see the group users, but client test can not.

![image](https://github.com/user-attachments/assets/850ff41d-2138-456c-8548-488abd249585)

NOTE THE SAME NAME "A" ON TOP OF THE WINDOW:

![image](https://github.com/user-attachments/assets/77da63df-e377-4cb9-960f-c59c68b2ef6e)

**Comment by paulasbia** [comment]
- [ ] When we connect by nc 127.0.0.1 <port>, we need send the command QUIT :Leaving twice, because on the first we did not disconnect:

![image](https://github.com/user-attachments/assets/33b1e71a-8a8e-434a-866d-5a70ce97c290)

**Comment by paulasbia** [comment]
- [ ] 

![image](https://github.com/user-attachments/assets/71522ef0-a2a5-4eee-8303-424228215c2c)

**Comment by taiscremaschi** [comment]
acho que isso é meu  por isso vou alterar o assigned pra mim

**Comment by taiscremaschi** [comment]
feito
