### ISSUE TITLE
A cast is necessary

### ISSUE THREAD

**Issue by paulasbia** [taiscremaschi/42_Irc#35]
## Context

The external function used was:
extern int setsockopt (int __fd, int __level, int __optname, const void *__optval, socklen_t __optlen) __THROW;

We need had a const void* optval and we used a int opt:

![image](https://github.com/user-attachments/assets/da6a21c8-83e0-4b5f-8355-ce8b55aeb11b)

## Where?
Server.cpp line 136.

## Question:
I observed that function has a exception, why we did not used?

**Comment by taiscremaschi** [comment]
a questao do void * é que uma variavel void * pode ser qualquer coisa... nesse caso precisa ser um int. agr muito bem observado a questao do throw... vou abrir uma branch pra fazer a gestao do catch
