### ISSUE TITLE
Error Handle

### ISSUE THREAD

**Issue by paulasbia** [taiscremaschi/42_Irc#36]
## Context

Error returns for getaddrinfo() and getnameinfo()

![image](https://github.com/user-attachments/assets/8f7704f6-92fa-4d74-8ce2-bee357c7444f)

## Question:
Why we did not use gai_strerror() function here?
![image](https://github.com/user-attachments/assets/2c479530-2ad5-4bde-aa93-46fb6f6da48b)

![image](https://github.com/user-attachments/assets/a6dcee1d-b6bb-408f-b538-7fd38829e9f5)

## Where?
Client.cpp Line 52

**Comment by Pac4games** [comment]
While the `gai_strerror()` function would serve our purpose better, it is an external function not listed in the project's subject, meaning we are most likely not allowed to use it. As a result, we had to "work our way around" that limitation.
