### ISSUE TITLE
History chat, are suppose?

### ISSUE THREAD

**Issue by paulasbia** [taiscremaschi/42_Irc#40]
Is it suppose that a user has the entire history of a group, even if we already started our server and client before?

Observe the history about #g1:
![image](https://github.com/user-attachments/assets/88d2ddd8-8d64-425c-bf01-d978fedef3d0)

**Comment by Pac4games** [comment]
This is an intended, default HexChat feature. It's behavior is to store the chat logs upon receiving them locally in the system. You can view the log files in `~/.config/hexchat/logs` or `~/.var/app/<HexChat package name here>/config/hexchat/logs`  (if it's installed as a Flatpak).
