### ISSUE TITLE
MODE +i (nc)

### ISSUE THREAD

**Issue by paulasbia** [taiscremaschi/42_Irc#41]
## Context

When a nc user join a new group (like operator) the first try to change MODE +i (invite necessary), we are starting +t (Topic) and other user can join this group without invite.

## How reproduce:

1. Start our server
2. Creates a client with HexChat
3. Creates a client with nc
4. With the nc client, join a group #g5 
5. Changes the MODE to +i
```
JOIN #g5
MODE #g5 +i
```
6. With the HexChat client, JOIN the group #g5
7. Note, the HexChat client joined #g5

![image](https://github.com/user-attachments/assets/d03b1915-fb38-4029-b8a7-154e81d3749a)

**Comment by Pac4games** [comment]
I have a question: this behavior of the channel automatically calling "mode +t" at creation was not implemented at first, and I did not read anywhere that it was supposed to happen. Is it a bug?

**Comment by Pac4games** [comment]
The "/mode +t" has been removed at the start of the channel in the #50 PR, so there is no need to answer that question. Please test if the issue is still present.
