### ISSUE TITLE
MODE +k/ +l (nc)

### ISSUE THREAD

**Issue by paulasbia** [taiscremaschi/42_Irc#42]
## Context

When a nc user join a new group (like operator) the first try to change MODE +k (Key necessary) or +l (limit), we are starting +t (Topic) and other user can join this group without key.

## How reproduce:

1. Start our server
2. Creates a client with HexChat
3. Creates a client with nc
4. With the nc client, join a group #g1
5. Changes the MODE to +k 123 (or +l 1)
```
JOIN #g5
MODE #g5 +k 123
```
6. With the HexChat client, JOIN the group #g1
7. Note, the HexChat client joined #g1 without a key

Mode +k 123:

![image](https://github.com/user-attachments/assets/da9e1f13-5bd6-4b5e-b07f-770c749f2d64)

Mode +l 1:

![image](https://github.com/user-attachments/assets/90ae9172-94c9-4943-a7d8-87bb25396c82)

**Comment by Pac4games** [comment]
#41
