### ISSUE TITLE
Use of functions not allowed in the project's subject.

### ISSUE THREAD

**Issue by Pac4games** [taiscremaschi/42_Irc#43]
While answering a previous issue, I have noticed that we currently use some external functions that are not listed by the project's subject. For reference, here is the list of allowed functions, that can also be found in the document in the root of the repository:

![image](https://github.com/user-attachments/assets/8b360b71-2b60-4f49-985c-b336f58d0c7f)

Some of the functions present in the current version of the project that are not included in this list are `getnameinfo()` and `getpeername()`, C functions part of the `sys/socket.h` and `netdb.h` libraries.

This needs to be changed before the project is submitted for evaluation.

**Comment by paulasbia** [comment]
The `getsockname()` and `getpeername()` system calls return, respectively, the local address to which a socket is bound and the address of the peer socket to which the local socket is connected.

The getsockname() function returns a socket’s address family and the address to which a socket is bound. This is useful if the socket was bound by another program (e.g., inetd(8)) and the socket file descriptor was then preserved across an exec().
Calling getsockname() is also useful if we want to determine the ephemeral port number that the kernel assigned to a socket when performing an implicit bind of an Internet domain socket. The kernel performs an implicit bind in the following circumstances:
1. after a connect() or a listen() call on a TCP socket that has not previously been bound to an address by bind();
2. on the first sendto() on a UDP socket that had not previously been bound to an
address; or
3. after a bind() call where the port number (sin_port) was specified as 0. In this case, the bind() specifies the IP address for the socket, but the kernel selects an ephemeral port number.

Is it possible to change to `getsocketname()`?

[Client.cpp line 51](https://github.com/taiscremaschi/42_Irc/blob/main/srcs/Client.cpp#L51): Is it really necessary?
```CPP
int result = getnameinfo((sockaddr*)&addr, addr_len, buff, sizeof(buff), NULL, 0, NI_NAMEREQD); // funtion to convert ip address into hostname. paramenters: endereço, size do address, buff para armazenar o host, size do buff, flag que idica a necesdidadedo hostname 

```

**Comment by taiscremaschi** [comment]
Neste momento estou com muitas issues pra resolver. @Pac4games  se tiveres tempo econseguires, tenta resolver essa issue
