### ISSUE TITLE
We only have one login attempt?

### ISSUE THREAD

**Issue by paulasbia** [taiscremaschi/42_Irc#45]
## Context

If we get the password wrong we are automatically disconnected:

![image](https://github.com/user-attachments/assets/913dfa17-9f95-40dd-b091-89939a307f99)

I think @taiscremaschi  put that in on purpose. I just want to confirm the defense

**Comment by taiscremaschi** [comment]
sim amiga.. é suposto sim... senao no hexchat da problema.. entao quando se erra a pass no nc, ele ja da quit.. isso esta correto
