### ISSUE TITLE
Seg. with CTRL + \

### ISSUE THREAD

**Issue by paulasbia** [taiscremaschi/42_Irc#64]
==14151== Memcheck, a memory error detector
==14151== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==14151== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==14151== Command: ./ircserv 8081 123
==14151== Parent PID: 14150
==14151== 
==14151== 
==14151== Process terminating with default action of signal 3 (SIGQUIT)
==14151==    at 0x4BD2B97: poll (poll.c:29)
==14151==    by 0x10C34A: Server::runServer() (Server.cpp:96)
==14151==    by 0x10C845: Server::inicializeServer() (Server.cpp:164)
==14151==    by 0x10BBBF: main (main.cpp:30)
==14151== 
==14151== HEAP SUMMARY:
==14151==     in use at exit: 73,736 bytes in 3 blocks
==14151==   total heap usage: 3 allocs, 0 frees, 73,736 bytes allocated
==14151== 
==14151== 8 bytes in 1 blocks are still reachable in loss record 1 of 3
==14151==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==14151==    by 0x10D931: __gnu_cxx::new_allocator<pollfd>::allocate(unsigned long, void const*) (new_allocator.h:127)
==14151==    by 0x10D752: __gnu_cxx::__alloc_traits<std::allocator<pollfd>, pollfd>::allocate(std::allocator<pollfd>&, unsigned long) (alloc_traits.h:133)
==14151==    by 0x10D545: std::_Vector_base<pollfd, std::allocator<pollfd> >::_M_allocate(unsigned long) (stl_vector.h:346)
==14151==    by 0x10D010: std::vector<pollfd, std::allocator<pollfd> >::_M_realloc_insert(__gnu_cxx::__normal_iterator<pollfd*, std::vector<pollfd, std::allocator<pollfd> > >, pollfd const&) (vector.tcc:440)
==14151==    by 0x10CCFF: std::vector<pollfd, std::allocator<pollfd> >::push_back(pollfd const&) (stl_vector.h:1198)
==14151==    by 0x10C839: Server::inicializeServer() (Server.cpp:163)
==14151==    by 0x10BBBF: main (main.cpp:30)
==14151== 
==14151== 1,024 bytes in 1 blocks are still reachable in loss record 2 of 3
==14151==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==14151==    by 0x4B38BA3: _IO_file_doallocate (filedoalloc.c:101)
==14151==    by 0x4B47CDF: _IO_doallocbuf (genops.c:347)
==14151==    by 0x4B46F5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==14151==    by 0x4B456D4: _IO_new_file_xsputn (fileops.c:1243)
==14151==    by 0x4B456D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==14151==    by 0x4B39FD6: fwrite (iofwrite.c:39)
==14151==    by 0x49AAB64: std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30)
==14151==    by 0x49AAEBA: std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30)
==14151==    by 0x10C812: Server::inicializeServer() (Server.cpp:159)
==14151==    by 0x10BBBF: main (main.cpp:30)
==14151== 
==14151== 72,704 bytes in 1 blocks are still reachable in loss record 3 of 3
==14151==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==14151==    by 0x4918939: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30)
==14151==    by 0x400647D: call_init.part.0 (dl-init.c:70)
==14151==    by 0x4006567: call_init (dl-init.c:33)
==14151==    by 0x4006567: _dl_init (dl-init.c:117)
==14151==    by 0x40202C9: ??? (in /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2)
==14151==    by 0x2: ???
==14151==    by 0x1FFEFFFBCA: ???
==14151==    by 0x1FFEFFFBD4: ???
==14151==    by 0x1FFEFFFBD9: ???
==14151== 
==14151== LEAK SUMMARY:
==14151==    definitely lost: 0 bytes in 0 blocks
==14151==    indirectly lost: 0 bytes in 0 blocks
==14151==      possibly lost: 0 bytes in 0 blocks
==14151==    still reachable: 73,736 bytes in 3 blocks
==14151==         suppressed: 0 bytes in 0 blocks
==14151== 
==14151== For lists of detected and suppressed errors, rerun with: -s
==14151== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by Pac4games** [comment]
"Ctrl+\\" sends the SIGQUIT signal to any running program. In the valgrind log provided, notice that the reason for process termination is stated as "Process terminating with default action of signal 3 (SIGQUIT)", which means, the default behavior is to dump the core and memory of the current program. You can test this with any other project (except minishell, in which we are obligated to handle this signal), and the same will happen.
